version: '3.7'

services:
  server:
    container_name: server
    # image: tiangolo/nginx-rtmp:latest
    build: ./nginx
    volumes:
      - ./nginx/server/nginx.conf:/etc/nginx/nginx.conf
      - ./data/raw:/tmp/raw
      - ./data/hls:/tmp/hls
      - ./data/rec:/tmp/rec
    ports:
      - "1935:1935"
      - "8000:8000"

  worker:
    container_name: worker
    build: ./nginx
    volumes:
      - ./nginx/worker/nginx.conf:/etc/nginx/nginx.conf
      - ./data/raw:/tmp/raw
      - ./data/hls:/tmp/hls
      - ./data/rec:/tmp/rec
      - ./nginx/scripts:/var/scripts
    depends_on:
      - server
